_wandb:
    value:
        cli_version: 0.21.0
        e:
            piubyngr6120r096cv59q1bfw1j885mc:
                codePath: rl/grpo_demo.py
                codePathLocal: grpo_demo.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1966736678912"
                        used: "173803524096"
                email: loganbolton101@gmail.com
                executable: /home/log/Github/post-train-moondream/.venv/bin/python
                git:
                    commit: f401a861946af2a525e2d7df4b86824e34eee10a
                    remote: https://github.com/LoganBolton/post-train-moondream
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-ae0db9b3-d710-87b1-6109-2223a6e2633b
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-e7528d81-29f1-0592-1333-a84d879b1a88
                host: log-linux
                memory:
                    total: "66473660416"
                os: Linux-6.11.0-29-generic-x86_64-with-glibc2.39
                program: /home/log/Github/post-train-moondream/rl/grpo_demo.py
                python: CPython 3.12.7
                root: /home/log/Github/post-train-moondream/rl
                startedAt: "2025-07-11T03:23:20.478704Z"
                writerId: piubyngr6120r096cv59q1bfw1j885mc
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "4": 3.12.7
            "5": 0.21.0
            "6": 4.53.1
            "12": 0.21.0
            "13": linux-x86_64
